# Generated by Django 4.2.7 on 2023-11-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='budget',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
