# Generated by Django 4.2.7 on 2023-11-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_book_budget_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
