# Generated by Django 4.2.7 on 2023-11-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0005_alter_book_is_best_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_best_selling',
            field=models.BooleanField(),
        ),
    ]
