# Generated by Django 4.2.7 on 2023-11-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0006_alter_book_is_best_selling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_best_selling',
        ),
    ]
