# Generated by Django 4.2.7 on 2023-11-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0008_book_is_best_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
